name: PR

on:
    pull_request:
        branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
    call-pr-workflow:
        uses: GaultOrg/.github/.github/workflows/pr.yml@main
